# Generated by Django 3.2.4 on 2021-06-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Blogpost',
        ),
    ]
